services:
  server:
    container_name: pills-bot-server
    image: ghcr.io/andrey-kondratov/pills-bot
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    env_file: ./server.env
    restart: unless-stopped
  
  db-init:
    container_name: pills-bot-db-init
    image: ghcr.io/andrey-kondratov/pills-bot
    depends_on:
      db:
        condition: service_healthy
    env_file: ./server.env
    entrypoint: /app/migrate
    
  db:
    container_name: pills-bot-db
    image: postgres:16.4-bookworm
    env_file: ./server.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
