name: Build

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=pr
      - name: Restore tools
        run: dotnet tool restore
      - name: Build
        run: dotnet cake
      - name: Push
        run: echo "${{ github.token }}" | dotnet cake --target Push --tag ${{ steps.meta.outputs.version }}
    
    outputs:
      server: ghcr.io
      registry: andrey-kondratov
      image: pills-bot
      version: ${{ steps.meta.outputs.version }}
  deploy:
    runs-on: rpi-media,arm64
    needs: build
    environment:
      name: bayard-test
    steps:
      - name: Update DockerCompose
        run: |
          cat << EOF > docker-compose.yml
          services:
            bot:
              image: ${{ needs.build.outputs.server }}/${{ needs.build.outputs.registry }}/${{ needs.build.outputs.image }}:${{ needs.build.outputs.version }}-arm64v8
              container_name: pills-bot
              environment:
                PILLSBOT__CONNECTION__APITOKEN: ${{ secrets.PILLSBOT__CONNECTION__APITOKEN }}
                PILLSBOT__CONNECTION__CHATID: "${{ secrets.PILLSBOT__CONNECTION__CHATID }}"
                PILLSBOT__REMINDER__INTERVAL: ${{ vars.PILLSBOT__REMINDER__INTERVAL }}
                PILLSBOT__AI__ENABLED: ${{ vars.PILLSBOT__AI__ENABLED }}
                PILLSBOT__AI__LANGUAGES: ${{ vars.PILLSBOT__AI__LANGUAGES }}
                PILLSBOT__AI__PETNAMES: ${{ secrets.PILLSBOT__AI__PETNAMES }}
                PILLSBOT__AI__PETGENDER: ${{ secrets.PILLSBOT__AI__PETGENDER }}
                PILLSBOT__AI__LOGLEVEL: ${{ vars.PILLSBOT__AI__LOGLEVEL }}
                PILLSBOT__AI__AZURE__ENDPOINT: ${{ secrets.PILLSBOT__AI__AZURE__ENDPOINT }}
                PILLSBOT__AI__AZURE__KEY: ${{ secrets.PILLSBOT__AI__AZURE__KEY }}
                PILLSBOT__AI__AZURE__DEPLOYMENTNAME: ${{ secrets.PILLSBOT__AI__AZURE__DEPLOYMENTNAME }}
              restart: unless-stopped
          EOF
      - name: Restart
        run: docker compose up --detach --pull always --quiet-pull --remove-orphans --wait --wait-timeout 60
