name: Build

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Restore tools
        run: dotnet tool restore
      - name: Install Docker-Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'
      - name: Build images
        run: dotnet cake docker.cake
